name: Deploy with Ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Update to a compatible version

    - name: Install dependencies
      run: |
        cd frontend
        npm install
        npm run build  # Build the frontend
        cd ../backend
        npm install

    - name: Start Backend Server
      run: |
        cd backend
        npx nodemon index.js &
        sleep 20

    - name: Start Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        npm install -g ngrok
        ngrok authtoken $NGROK_AUTH_TOKEN
        ngrok http 5000 &

    - name: Display Ngrok URL
      run: |
        sleep 5
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Keep Action Alive
      run: |
        while true; do sleep 30; done
