name: Deploy with Ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend
        npm install
        npm run build
        cd ../backend
        npm install

    - name: Start Backend Server
      run: |
        cd backend
        npx nodemon index.js &
        sleep 20

    - name: Start Ngrok with Custom Domain
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        npm install -g ngrok
        ngrok authtoken $NGROK_AUTH_TOKEN
        ngrok http --hostname=cunning-slightly-primate.ngrok-free.app 5000 &
        sleep 5

    - name: Display Ngrok URL
      run: echo "Your Ngrok URL is: https://cunning-slightly-primate.ngrok-free.app"

    - name: Keep Action Alive
      run: |
        echo "Keeping the action alive for up to 6 hours..."
        timeout=21600  # 6 hours in seconds
        while [ $timeout -gt 0 ]; do
          sleep 30
          timeout=$((timeout - 30))
        done
